---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tempsensor
spec:
  selector:
    matchLabels:
      app: tempSensor
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: tempSensor
      annotations:
        isEdgeDeployment: "true"
        targetCondition: "tags.building='b43'"
        priority: "15"
        loggingOptions: ""
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tempSensor
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: tempsensor
        image: "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0"
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: iotedge
        effect: NoSchedule
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "route": "FROM /* INTO $upstream"
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 7200
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tempsensor
data:
  status: running
  restartPolicy: on-unhealthy
  version: "1.0"
  createOptions: |
    {
      "HostConfig": {
        "PortBindings": {
          "27017/tcp": [
            {
              "HostPort": "27017"
            }
          ]
        }
      }
    }
  desiredProperties: |
    {
      "boo": "bah"
    }
---
